### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by QuantumApprentice** [KeyboardGecko/Fallout-Nevada-Translation#1]
https://github.com/KeyboardGecko/Fallout-Nevada-Translation/blob/cfc8f8f6a0f506e20093092ab50f6af613b2d113/text/english/dialog/ncmusor.msg#L158
Change
"he tries to catch him breath"
to
"he tries to catch his breath"

**Comment by QuantumApprentice** [comment]
sorry, this is my first time so I'm not sure how to submit a fixed dialogue...

**Comment by KeyboardGecko** [comment]
Just make changes and commit them. I will describe how to make this easier a little later

**Comment by QuantumApprentice** [comment]
I was trying to figure out the process and stepienz was showing me this roundabout way.  I'd love to hear how to do this correctly, I'm still new to github and programming in general.
