### ISSUE TITLE
"master debater"?

### ISSUE THREAD

**Issue by QuantumApprentice** [KeyboardGecko/Fallout-Nevada-Translation#12]
https://github.com/KeyboardGecko/Fallout-Nevada-Translation/blob/6485cb460457c62151fc5546a411b12f2a09a97f/text/english/dialog/rcnlspwr.msg#L12

lol is this intentional? it's a great joke if it is, but I just gotta know :P

**Comment by KeyboardGecko** [comment]
More like an accident, I think) originally it was "I see you are an experienced negotiator"

**Comment by QuantumApprentice** [comment]
lol if only "master debater" worked here :P
