### ISSUE TITLE
Faulty line w/ Thompson's gunsmith

### ISSUE THREAD

**Issue by bgaesslein** [KeyboardGecko/Fallout-Nevada-Translation#14]
https://github.com/KeyboardGecko/Fallout-Nevada-Translation/blob/9382d5f65d49b46be6d9861ab7b8a2eaecc8d4bd/text/english/dialog/nctomamm.msg#L56

This looks like something Thompson should say but it's a dialog option for the player. Not sure how to best fix this

![image](https://user-images.githubusercontent.com/86594273/201747270-d1cf8530-c6e3-4556-b6ee-03617681fbd3.png)

**Comment by KeyboardGecko** [comment]
Fixed, thanks for the report!
